name: CI CD Workflow
on: push
jobs:
  CodeCheckout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Execute Tests
        run: npm test
  Deployment:
    needs: CodeCheckout
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Code
        run: echo "Deploying"
  AutomationTest:
    needs: [CodeCheckout, Deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Code
        run: echo "Deploying"      

